CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID)) TYPE = innodb;
CREATE TABLE TEMPO_ITEM (id BIGINT NOT NULL, content_type VARCHAR(255), payload BLOB, uri VARCHAR(255), PRIMARY KEY (id)) TYPE = innodb;
