package org.intalio.tempo.uiframework.export;

public enum ExportKey {
    CREATION_DATE, DESCRIPTION, ID, FORM_URL, PRIORITY, STATE, PROCESS_ID, PROCESS_ENDPOINT, INIT_MESSAGE_NS, INIT_OPERATION_ACTION, COMPLETE_URL, DEADLINE
}
