<?xml version="1.0" encoding="UTF-8"?><!--
  ~ Copyright (c) 2005-2007 Intalio inc.
  ~
  ~ All rights reserved. This program and the accompanying materials
  ~ are made available under the terms of the Eclipse Public License v1.0
  ~ which accompanies this distribution, and is available at
  ~ http://www.eclipse.org/legal/epl-v10.html
  ~
  ~ Contributors:
  ~ Intalio inc. - initial API and implementation
  -->

<wsdl:definitions name="AbsenceRequest_To_Employee" targetNamespace="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Employee" xmlns:tns="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Employee" xmlns:ns0="http://www.intalio.com/workflow/forms/AbsenceRequest/Notification" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"><import namespace="http://www.intalio.com/workflow/forms/AbsenceRequest/Notification" schemaLocation="Notification.xform.notify.xsd"/></schema>
  </wsdl:types>
  <wsdl:message name="NotifyResponse">
    <wsdl:part name="notifyResponse" element="ns0:notifyResponse"/>
  </wsdl:message>
  <wsdl:message name="NotifyRequest">
    <wsdl:part name="notifyRequest" element="ns0:notifyRequest"/>
  </wsdl:message>
  <wsdl:portType name="AbsenceRequest_To_Employee_PortType">
    <wsdl:operation name="Receive_Notification">
      <wsdl:input name="NotifyRequest" message="tns:NotifyRequest"/>
      <wsdl:output name="NotifyResponse" message="tns:NotifyResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AbsenceRequest_To_Employee_Binding" type="tns:AbsenceRequest_To_Employee_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Receive_Notification">
      <soap:operation soapAction="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Employee/AbsenceRequest_To_Employee_PortType/Receive_Notification" style="document"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Employee"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" namespace="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Employee"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AbsenceRequest_To_Employee_Service">
    <wsdl:port name="AbsenceRequest_To_Employee_Http" binding="tns:AbsenceRequest_To_Employee_Binding">
      <soap:address location="http://localhost:8080/fds/workflow"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
