<?xml version="1.0" encoding="UTF-8"?><!--
  ~ Copyright (c) 2005-2007 Intalio inc.
  ~
  ~ All rights reserved. This program and the accompanying materials
  ~ are made available under the terms of the Eclipse Public License v1.0
  ~ which accompanies this distribution, and is available at
  ~ http://www.eclipse.org/legal/epl-v10.html
  ~
  ~ Contributors:
  ~ Intalio inc. - initial API and implementation
  -->

<wsdl:definitions name="AbsenceRequest_To_Manager" targetNamespace="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Manager" xmlns:tns="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Manager" xmlns:ns0="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"><import namespace="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest" schemaLocation="AbsenceApproval.xform.create.xsd"/></schema>
  </wsdl:types>
  <wsdl:message name="createTaskResponse">
    <wsdl:part name="response" element="ns0:response"/>
  </wsdl:message>
  <wsdl:message name="createTaskRequest">
    <wsdl:part name="createTaskRequest" element="ns0:createTaskRequest"/>
  </wsdl:message>
  <wsdl:portType name="AbsenceRequest_To_Manager_PortType">
    <wsdl:operation name="Receive_Absence_Request--006">
      <wsdl:input name="createTaskRequest" message="tns:createTaskRequest"/>
      <wsdl:output name="createTaskResponse" message="tns:createTaskResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AbsenceRequest_To_Manager_Binding" type="tns:AbsenceRequest_To_Manager_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Receive_Absence_Request--006">
      <soap:operation soapAction="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Manager/AbsenceRequest_To_Manager_PortType/Receive_Absence_Request--006" style="document"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Manager"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" namespace="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Manager"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AbsenceRequest_To_Manager_Service">
    <wsdl:port name="AbsenceRequest_To_Manager_Http" binding="tns:AbsenceRequest_To_Manager_Binding">
      <soap:address location="http://localhost:8080/fds/workflow/examples/AbsenceRequest"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
