<?xml version="1.0" encoding="UTF-8"?><!--
  ~ Copyright (c) 2005-2007 Intalio inc.
  ~
  ~ All rights reserved. This program and the accompanying materials
  ~ are made available under the terms of the Eclipse Public License v1.0
  ~ which accompanies this distribution, and is available at
  ~ http://www.eclipse.org/legal/epl-v10.html
  ~
  ~ Contributors:
  ~ Intalio inc. - initial API and implementation
  -->

<wsdl:definitions name="AbsenceRequest_And_Manager_PLT" targetNamespace="http://www.example.com/AbsenceRequest/AbsenceRequest_And_Manager_PLT" xmlns:tns="http://www.example.com/AbsenceRequest/AbsenceRequest_And_Manager_PLT" xmlns:portTypeNS2="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Manager" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:portTypeNS1="http://www.example.com/AbsenceRequest/Manager_To_AbsenceRequest" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.example.com/AbsenceRequest/Manager_To_AbsenceRequest" location="AbsenceRequest-Manager_To_AbsenceRequest.wsdl"/>
  <wsdl:import namespace="http://www.example.com/AbsenceRequest/AbsenceRequest_To_Manager" location="AbsenceRequest-AbsenceRequest_To_Manager.wsdl"/>
<plnk:partnerLinkType name="AbsenceRequest_And_Manager_PLT">
    <plnk:role name="AbsenceRequest_Role" portType="portTypeNS1:Manager_To_AbsenceRequest_PortType"/>
    <plnk:role name="Manager_Role" portType="portTypeNS2:AbsenceRequest_To_Manager_PortType"/>
</plnk:partnerLinkType>
</wsdl:definitions>
