<?xml version="1.0" encoding="UTF-8"?><!--
  ~ Copyright (c) 2005-2007 Intalio inc.
  ~
  ~ All rights reserved. This program and the accompanying materials
  ~ are made available under the terms of the Eclipse Public License v1.0
  ~ which accompanies this distribution, and is available at
  ~ http://www.eclipse.org/legal/epl-v10.html
  ~
  ~ Contributors:
  ~ Intalio inc. - initial API and implementation
  -->

<wsdl:definitions name="Manager_To_AbsenceRequest" targetNamespace="http://www.example.com/AbsenceRequest/Manager_To_AbsenceRequest" xmlns:tns="http://www.example.com/AbsenceRequest/Manager_To_AbsenceRequest" xmlns:ns0="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"><import namespace="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest" schemaLocation="AbsenceApproval.xform.complete.xsd"/></schema>
  </wsdl:types>
  <wsdl:message name="notifyTaskCompletionResponse">
    <wsdl:part name="response" element="ns0:response"/>
  </wsdl:message>
  <wsdl:message name="notifyTaskCompletionRequest">
    <wsdl:part name="notifyTaskCompletionRequest" element="ns0:notifyTaskCompletionRequest"/>
  </wsdl:message>
  <wsdl:portType name="Manager_To_AbsenceRequest_PortType">
    <wsdl:operation name="Receive_Manager_Approval">
      <wsdl:input name="notifyTaskCompletionRequest" message="tns:notifyTaskCompletionRequest"/>
      <wsdl:output name="notifyTaskCompletionResponse" message="tns:notifyTaskCompletionResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Manager_To_AbsenceRequest_Binding" type="tns:Manager_To_AbsenceRequest_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Receive_Manager_Approval">
      <soap:operation soapAction="http://www.example.com/AbsenceRequest/Manager_To_AbsenceRequest/Manager_To_AbsenceRequest_PortType/Receive_Manager_Approval" style="document"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://www.example.com/AbsenceRequest/Manager_To_AbsenceRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" namespace="http://www.example.com/AbsenceRequest/Manager_To_AbsenceRequest"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Manager_To_AbsenceRequest_Service">
    <wsdl:port name="Manager_To_AbsenceRequest_Http" binding="tns:Manager_To_AbsenceRequest_Binding">
      <soap:address location="http://localhost:8080/ode/processes/AbsenceRequest/Manager_To_AbsenceRequest"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
