<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2005-2007 Intalio inc.
  ~
  ~ All rights reserved. This program and the accompanying materials
  ~ are made available under the terms of the Eclipse Public License v1.0
  ~ which accompanies this distribution, and is available at
  ~ http://www.eclipse.org/legal/epl-v10.html
  ~
  ~ Contributors:
  ~ Intalio inc. - initial API and implementation
  -->
<wsdl:definitions
  targetNamespace="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:ar="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="AbsenceApproval.xform.init.xsd" namespace="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest"/>
  <wsdl:types/>
  <!-- Messages -->
  <wsdl:message name="initProcessRequest">
    <wsdl:part element="ar:initProcessRequest" name="root"/>
  </wsdl:message>
  <wsdl:message name="initProcessResponse">
    <wsdl:part element="ar:initProcessResponse" name="root"/>
  </wsdl:message>
  <!-- Port Types -->
  <wsdl:portType name="userProcessPortType">
    <wsdl:operation name="initProcess">
      <wsdl:input message="ar:initProcessRequest" name="initProcessRequest"/>
      <wsdl:output message="ar:initProcessResponse" name="initProcessResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <!-- SOAP Bindings -->
  <wsdl:binding name="userProcessSoapBinding" type="ar:userProcessPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="initProcess">
      <soap:operation soapAction="initProcess" style="document"/>
      <wsdl:input>
        <soap:body
          namespace="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body
          namespace="http://www.intalio.com/workflow/forms/AbsenceRequest/AbsenceRequest" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <!-- Services -->
  <wsdl:service name="initProcessService">
    <wsdl:port binding="ar:userProcessSoapBinding" name="userProcessPort">
      <soap:address location="http://example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
