CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE TEMPO_ITEM (id BIGINT NOT NULL, content_type VARCHAR(254), lastmodified TIMESTAMP, payload BLOB, uri VARCHAR(254), PRIMARY KEY (id));
CREATE UNIQUE INDEX OPENJPA_SEQUENCE_TABLE_IDX ON OPENJPA_SEQUENCE_TABLE (ID);
