<?xml version='1.0' encoding='utf-8'?>
<wsdl:definitions xmlns:attachments="http://www.intalio.com/gi/forms/TAlistExport.gi/attachments" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:TAlistExport="http://www.intalio.com/gi/forms/TAlistExport.gi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:process="http://example.com/process/StartTAlistExport/process" xmlns:diag="http://example.com/process/StartTAlistExport" xmlns:User="http://example.com/process/StartTAlistExport/User" xmlns:TAlistToAMI-TAlistExportProcess="http://example.com/process/TAlistToAMI/TAlistExportProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:pnlk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:bpdm="http://www.intalio/designer/business-process-data-modeling" targetNamespace="http://example.com/process/StartTAlistExport">
    <wsdl:import namespace="http://example.com/process/TAlistToAMI/TAlistExportProcess" location="TAlistToAMI-TAlistExportProcess.wsdl"/>
    <wsdl:import namespace="http://www.intalio.com/gi/forms/TAlistExport.gi" location="../forms/TAlistExport.gi.wsdl"/>
    <pnlk:partnerLinkType name="processAndUserForPortTypeProcessPlk">
        <pnlk:role name="process_for_User" portType="TAlistExport:Process"/>
    </pnlk:partnerLinkType>
    <pnlk:partnerLinkType name="processimplicitPartnerAndProcessForCanonicPortPlk">
        <pnlk:role name="processimplicitPartner_for_process" portType="TAlistToAMI-TAlistExportProcess:ForTAinterface"/>
    </pnlk:partnerLinkType>
</wsdl:definitions>