<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PA" targetNamespace="http://www.example.com/PA" xmlns:bpws="http://schemas.xmlsoap.org/ws/2004/03/business-process/" xmlns:tns="http://www.example.com/PA" xmlns:Start="http://www.example.com/Start--004_To_PA" xmlns:PA="http://www.intalio.com/bpms/workflow/xforms/PeopleActivity/PA" xmlns:User="http://www.example.com/PA_To_User" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:this="http://www.example.com/PA" xmlns:User1="http://www.example.com/User_To_PA">
  <wsdl:import namespace="http://www.example.com/User_To_PA" location="PA-User_To_PA.wsdl"/>
  <wsdl:import namespace="http://www.example.com/PA_And_Start--004_PLT" location="PA-PA_And_Start--004_PLT.wsdl"/>
  <wsdl:import namespace="http://www.example.com/PA_And_User_PLT" location="PA-PA_And_User_PLT.wsdl"/>
  <wsdl:import namespace="http://www.example.com/Start--004_To_PA" location="PA-Start--004_To_PA.wsdl"/>
  <wsdl:import namespace="http://www.example.com/PA_To_User" location="PA-PA_To_User.wsdl"/>
<bpws:property name="taskIdProp" type="xs:string"/>
<bpws:propertyAlias messageType="User:createTaskResponse" part="response" propertyName="this:taskIdProp">
    <bpws:query>PA:taskMetaData/PA:taskId/text()</bpws:query>
</bpws:propertyAlias>
<bpws:propertyAlias messageType="User1:notifyTaskCompletionRequest" part="notifyTaskCompletionRequest" propertyName="this:taskIdProp">
    <bpws:query>PA:taskMetaData/PA:taskId/text()</bpws:query>
</bpws:propertyAlias>
</wsdl:definitions>
