<?xml version="1.0" encoding="UTF-8"?><!--
  ~ Copyright (c) 2005-2007 Intalio inc.
  ~
  ~ All rights reserved. This program and the accompanying materials
  ~ are made available under the terms of the Eclipse Public License v1.0
  ~ which accompanies this distribution, and is available at
  ~ http://www.eclipse.org/legal/epl-v10.html
  ~
  ~ Contributors:
  ~ Intalio inc. - initial API and implementation
  -->

<wsdl:definitions name="PA_And_Start--004_PLT" targetNamespace="http://www.example.com/PA_And_Start--004_PLT" xmlns:tns="http://www.example.com/PA_And_Start--004_PLT" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:portTypeNS1="http://www.example.com/Start--004_To_PA" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.example.com/Start--004_To_PA" location="PA-Start--004_To_PA.wsdl"/>
<plnk:partnerLinkType name="PA_And_Start--004_PLT">
    <plnk:role name="PA_Role" portType="portTypeNS1:Start--004_To_PA_PortType"/>
</plnk:partnerLinkType>
</wsdl:definitions>
