<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PA_And_User_PLT" targetNamespace="http://www.example.com/PA_And_User_PLT" xmlns:tns="http://www.example.com/PA_And_User_PLT" xmlns:portTypeNS2="http://www.example.com/PA_To_User" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:portTypeNS1="http://www.example.com/User_To_PA" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.example.com/User_To_PA" location="PA-User_To_PA.wsdl"/>
  <wsdl:import namespace="http://www.example.com/PA_To_User" location="PA-PA_To_User.wsdl"/>
<plnk:partnerLinkType name="PA_And_User_PLT">
    <plnk:role name="User_Role" portType="portTypeNS2:PA_To_User_PortType"/>
    <plnk:role name="PA_Role" portType="portTypeNS1:User_To_PA_PortType"/>
</plnk:partnerLinkType>
</wsdl:definitions>
