<?xml version="1.0" encoding="UTF-8"?><!--
  ~ Copyright (c) 2005-2007 Intalio inc.
  ~
  ~ All rights reserved. This program and the accompanying materials
  ~ are made available under the terms of the Eclipse Public License v1.0
  ~ which accompanies this distribution, and is available at
  ~ http://www.eclipse.org/legal/epl-v10.html
  ~
  ~ Contributors:
  ~ Intalio inc. - initial API and implementation
  -->

<wsdl:definitions name="userProcessPort_To_Pool" targetNamespace="http://www.intalio.com/bpms/workflow/xforms/PIPA/startform" xmlns:tns="http://www.intalio.com/bpms/workflow/xforms/PIPA/startform" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <import namespace="http://www.intalio.com/bpms/workflow/xforms/PIPA/startform" schemaLocation="startform.xform.init.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="initProcessRequest">
    <wsdl:part name="initProcessRequest" element="tns:initProcessRequest"/>
  </wsdl:message>
  <wsdl:message name="initProcessResponse">
    <wsdl:part name="initProcessResponse" element="tns:initProcessResponse"/>
  </wsdl:message>
  <wsdl:portType name="userProcessPort_To_Pool_PortType">
    <wsdl:operation name="startTask">
      <wsdl:input message="tns:initProcessRequest"/>
      <wsdl:output message="tns:initProcessResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="userProcessPort_To_Pool_Binding" type="tns:userProcessPort_To_Pool_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="startTask">
      <soap:operation soapAction="http://www.intalio.com/bpms/workflow/xforms/PIPA/startform/userProcessPort_To_Pool_PortType/startTask" style="document"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://www.intalio.com/bpms/workflow/xforms/PIPA/startform"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" namespace="http://www.intalio.com/bpms/workflow/xforms/PIPA/startform"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="userProcessPort_To_Pool_Service">
    <wsdl:port name="userProcessPort_To_Pool_Http" binding="tns:userProcessPort_To_Pool_Binding">
      <soap:address location="http://localhost:8080/pxe/soap/userProcessPort_To_Pool"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
