/* Generated By:JJTree: Do not edit this line. ASTFunNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.intalio.tempo.workflow.tmsb4p.parser;

public class ASTFunNode extends SimpleNode {
	/**
	 * Function name
	 */
	private String name;
  public ASTFunNode(int id) {
    super(id);
  }

  public ASTFunNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
    return visitor.visit(this, data);
  }
  
	public void setFunction(String name) {
		this.name = name;
	}

	public String toString() {
		return "Function: " + name;
	}
	
	public String getName() {
		return name;
	}
	
  public String getNodeName() {
		return ParserTreeConstants.jjtNodeName[ParserTreeConstants.JJTFUNNODE];
	}
}
/* JavaCC - OriginalChecksum=e541e512c6599a32fb86d41553ba1521 (do not edit this line) */
