/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.intalio.tempo.workflow.tmsb4p.parser;

public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
    return visitor.visit(this, data);
  }
  
  public String getNodeName() {
		return ParserTreeConstants.jjtNodeName[ParserTreeConstants.JJTSTART];
	}
}
/* JavaCC - OriginalChecksum=d2458ef26e61234af700e553d9f694af (do not edit this line) */
