/* Generated By:JJTree: Do not edit this line. ASTVarNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.intalio.tempo.workflow.tmsb4p.parser;

public class ASTVarNode extends SimpleNode {
	private String value;
  public ASTVarNode(int id) {
    super(id);
  }

  public ASTVarNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
    return visitor.visit(this, data);
  }
  
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String toString() {
		return "Variable: " + value;
	}

	public String getNodeName() {
		return ParserTreeConstants.jjtNodeName[ParserTreeConstants.JJTVARNODE];
	}
}
/* JavaCC - OriginalChecksum=61538543cef521dfb4a850a2499af7d4 (do not edit this line) */
