/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 4.1d1 */
package org.intalio.tempo.workflow.tmsb4p.parser;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws ParseException;
  public Object visit(ASTStart node, Object data) throws ParseException;
  public Object visit(ASTFunNode node, Object data) throws ParseException;
  public Object visit(ASTVarNode node, Object data) throws ParseException;
  public Object visit(ASTArray node, Object data) throws ParseException;
  public Object visit(ASTConstant node, Object data) throws ParseException;
}
/* JavaCC - OriginalChecksum=3345b6400c53bdcde26c25a45ab96695 (do not edit this line) */
