/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 4.2 */
package org.intalio.tempo.workflow.tmsb4p.parser;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws ParseException;
  public Object visit(ASTStart node, Object data) throws ParseException;
  public Object visit(ASTFunNode node, Object data) throws ParseException;
  public Object visit(ASTVarNode node, Object data) throws ParseException;
  public Object visit(ASTArray node, Object data) throws ParseException;
  public Object visit(ASTConstant node, Object data) throws ParseException;
}
/* JavaCC - OriginalChecksum=abd3d322b1cdb70530a95175c656fd77 (do not edit this line) */
