/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.2 */
package org.intalio.tempo.workflow.tmsb4p.parser;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNNODE = 2;
  public int JJTVARNODE = 3;
  public int JJTARRAY = 4;
  public int JJTCONSTANT = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "FunNode",
    "VarNode",
    "Array",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=774fb018c1877e2d334cb8dc8ef03055 (do not edit this line) */
