/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
package org.intalio.tempo.workflow.tmsb4p.parser;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNNODE = 2;
  public int JJTVARNODE = 3;
  public int JJTARRAY = 4;
  public int JJTCONSTANT = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "FunNode",
    "VarNode",
    "Array",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=d8785e98975e56f8b6b874ca4a1bfbda (do not edit this line) */
