<wsdl:definitions targetNamespace="urn:intalio.com:connectors:database:sita:countexistingtasservice" xmlns:tns="urn:intalio.com:connectors:database:sita:countexistingtasservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:intalio.com:connectors:database:sita:countexistingtasservice">
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="countExistingTAs.xsd" namespace="urn:intalio.com:connectors:database:sita:countexistingtasservice"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="countExistingTAsInput">
        <wsdl:part name="parameters" element="ns:countExistingTAsParameterSet"/>
    </wsdl:message>
    <wsdl:message name="countExistingTAsOutput">
        <wsdl:part name="parameters" element="ns:countExistingTAsResultSet"/>
    </wsdl:message>
    <wsdl:portType name="countExistingTAsPort">
        <wsdl:operation name="countExistingTAs">
            <wsdl:input message="tns:countExistingTAsInput"/>
            <wsdl:output message="tns:countExistingTAsOutput"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="countExistingTAsPortSoapBinding" type="tns:countExistingTAsPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="countExistingTAs">
            <soap:operation style="document" soapAction="urn:intalio:connector:jdbc:query:countExistingTAs"/>
            <wsdl:input>
                <soap:body namespace="urn:intalio.com:connectors:database:sita:countexistingtasservice" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="urn:intalio.com:connectors:database:sita:countexistingtasservice" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="countExistingTAsService">
        <wsdl:port binding="tns:countExistingTAsPortSoapBinding" name="countExistingTAsPort">
            <soap:address location="http://172.17.128.120:9080/ode/processes/SITA/database/countExistingTAs"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>