<?xml version='1.0' encoding='utf-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:NotifInterface="http://example.com/process/NotifToAMI/NotifInterface" xmlns:ami-notification="http://www.example.org/notif" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:diag="http://example.com/process/NotifToAMI" xmlns:tns="http://ode/bpel/unit-test.wsdl" xmlns:nf="http://www.example.org/notif" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:pnlk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:this="http://example.com/process/NotifToAMI/NotifToAMIprocess" xmlns:RMAnotifService="http://example.com/process/NotifToAMI/RMAnotifService" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://example.com/process/NotifToAMI/NotifToAMIprocess">
    <wsdl:types>
        <xs:schema targetNamespace="http://www.example.org/notif">
            <xs:include schemaLocation="../schema/ami-notification.xsd"/>
        </xs:schema>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://example.com/process/NotifToAMI/NotifToAMIprocess">
            <xs:element name="startResponse" type="xs:string"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="startRequest">
        <wsdl:part name="body" element="nf:notifData"/>
    </wsdl:message>
    <wsdl:message name="startResponse">
        <wsdl:part name="body" element="this:startResponse"/>
    </wsdl:message>
    <wsdl:portType name="ForNotifInterface">
        <wsdl:operation name="start">
            <wsdl:input message="this:startRequest" name="start"/>
            <wsdl:output message="this:startResponse" name="startResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CanonicBindingForNotifInterface" type="this:ForNotifInterface">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="start">
            <soap:operation style="document" soapAction="http://example.com/process/NotifToAMI/NotifToAMIprocess/ForNotifInterface/start"/>
            <wsdl:input name="start">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="startResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CanonicServiceForNotifInterface">
        <wsdl:port name="canonicPort" binding="this:CanonicBindingForNotifInterface">
            <soap:address location="http://localhost:9080/ode/processes/SITA/process/NotifToAMI/NotifToAMIprocess/NotifInterface"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>