<wsdl:definitions targetNamespace="urn:intalio.com:connectors:database:sita:getallmechsservice" xmlns:tns="urn:intalio.com:connectors:database:sita:getallmechsservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:intalio.com:connectors:database:sita:getallmechsservice">
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="getAllMechs.xsd" namespace="urn:intalio.com:connectors:database:sita:getallmechsservice"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getAllMechsInput">
        <wsdl:part name="parameters" element="ns:getAllMechsParameterSet"/>
    </wsdl:message>
    <wsdl:message name="getAllMechsOutput">
        <wsdl:part name="parameters" element="ns:getAllMechsResultSet"/>
    </wsdl:message>
    <wsdl:portType name="getAllMechsPort">
        <wsdl:operation name="getAllMechs">
            <wsdl:input message="tns:getAllMechsInput"/>
            <wsdl:output message="tns:getAllMechsOutput"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="getAllMechsPortSoapBinding" type="tns:getAllMechsPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getAllMechs">
            <soap:operation style="document" soapAction="urn:intalio:connector:jdbc:query:getAllMechs"/>
            <wsdl:input>
                <soap:body namespace="urn:intalio.com:connectors:database:sita:getallmechsservice" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="urn:intalio.com:connectors:database:sita:getallmechsservice" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="getAllMechsService">
        <wsdl:port binding="tns:getAllMechsPortSoapBinding" name="getAllMechsPort">
            <soap:address location="http://172.17.128.120:9080/ode/processes/SITA/database/getAllMechs"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>