<wsdl:definitions targetNamespace="urn:intalio.com:connectors:database:sita:getallavisservice" xmlns:tns="urn:intalio.com:connectors:database:sita:getallavisservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:intalio.com:connectors:database:sita:getallavisservice">
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="getAllAvis.xsd" namespace="urn:intalio.com:connectors:database:sita:getallavisservice"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getAllAvisInput">
        <wsdl:part name="parameters" element="ns:getAllAvisParameterSet"/>
    </wsdl:message>
    <wsdl:message name="getAllAvisOutput">
        <wsdl:part name="parameters" element="ns:getAllAvisResultSet"/>
    </wsdl:message>
    <wsdl:portType name="getAllAvisPort">
        <wsdl:operation name="getAllAvis">
            <wsdl:input message="tns:getAllAvisInput"/>
            <wsdl:output message="tns:getAllAvisOutput"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="getAllAvisPortSoapBinding" type="tns:getAllAvisPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getAllAvis">
            <soap:operation style="document" soapAction="urn:intalio:connector:jdbc:query:getAllAvis"/>
            <wsdl:input>
                <soap:body namespace="urn:intalio.com:connectors:database:sita:getallavisservice" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="urn:intalio.com:connectors:database:sita:getallavisservice" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="getAllAvisService">
        <wsdl:port binding="tns:getAllAvisPortSoapBinding" name="getAllAvisPort">
            <soap:address location="http://172.17.128.120:9080/ode/processes/SITA/database/getAllAvis"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>