<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions targetNamespace="http://ode/bpel/unit-test.wsdl"
	xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ode/bpel/unit-test.wsdl"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:nf="http://www.example.org/notif">
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.example.org/notif">
			<xsd:include schemaLocation="../schema/ami-notification.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="RMAnotif">
		<wsdl:part name="body" element="nf:notification" />
	</wsdl:message>

	<wsdl:portType name="RMAnotifPortType">
		<wsdl:operation name="sendRMAnotif">
			<wsdl:input message="tns:RMAnotif" name="inputMessage" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="RMAnotifSoapBinding" type="tns:RMAnotifPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="sendRMAnotif">
			<soap:operation soapAction="" style="document" />
			<wsdl:input>
				<soap:body namespace="http://ode/bpel/unit-test.wsdl" use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="RMAnotifService">
		<wsdl:port name="RMAnotifPort" binding="tns:RMAnotifSoapBinding">
			<soap:address
				location="jms:/so.msg.queue?transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory&amp;java.naming.factory.initial=org.apache.activemq.jndi.ActiveMQInitialContextFactory&amp;java.naming.provider.url=tcp://localhost:61616&amp;transport.jms.ReplyDestinationType=queue&amp;transport.jms.DestinationType=queue" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>