<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions targetNamespace="http://ode/bpel/unit-test.wsdl"
	xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ode/bpel/unit-test.wsdl"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ta="http://www.example.org/ta">
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.example.org/ta">
			<xsd:include schemaLocation="../schema/ami-ta-list.xsd" />
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="TAlist">
		<wsdl:part name="body" element="ta:ta-list" />
	</wsdl:message>

	<wsdl:portType name="TAlistPortType">
		<wsdl:operation name="sendTAlist">
			<wsdl:input message="tns:TAlist" name="inputMessage" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="TAlistSoapBinding" type="tns:TAlistPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="sendTAlist">
			<soap:operation soapAction="" style="document" />
			<wsdl:input>
				<soap:body namespace="http://ode/bpel/unit-test.wsdl" use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="TAlistService">
		<wsdl:port name="TAlistPort" binding="tns:TAlistSoapBinding">
			<soap:address
				location="jms:/so.tasks.queue?transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory&amp;java.naming.factory.initial=org.apache.activemq.jndi.ActiveMQInitialContextFactory&amp;java.naming.provider.url=tcp://localhost:61616&amp;transport.jms.ReplyDestinationType=queue&amp;transport.jms.DestinationType=queue" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>