CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE TEMPO_ITEM -- Item
    (id BIGINT NOT NULL, -- datastore id
    content_type VARCHAR(255), lastmodified TIMESTAMP, payload BLOB, uri VARCHAR(255), PRIMARY KEY (id));
