require "rubygems"
require "buildr"

# Keep this structure to allow the build system to update version numbers.
VERSION_NUMBER = "6.0.1-SNAPSHOT"

require "../rsc/build/repositories.rb"

desc "Tempo Workflow"
define "tempo" do
  project.version = VERSION_NUMBER
  project.group = "org.intalio.tempo"
  
  desc "Workflow Processes"
  define "processes" do
    define "xpath-extensions" do
      package :jar
    end
    
    define "AbsenceRequest" do
      package :jar
    end
    
    define "TaskManager" do
      package :jar
    end
  end
end
