<?xml version='1.0' encoding='utf-8'?>
<wsdl:definitions xmlns:TaskManagementProcess="http://example.com/TMP/TaskManagementProcess" xmlns:UserBusinessProcess="http://www.intalio.com/bpms/ubp" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:b4px="java:org.intalio.tempo.workflow.processes.xpath.UID" xmlns:b4px1="http://oracle.com/the/custom/functions" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:b4p="http://www.intalio.com/bpms/workflow/ib4p_20051115" xmlns:bpdm="http://www.intalio/designer/business-process-data-modeling" xmlns:bpel="http://schemas.xmlsoap.org/ws/2004/03/business-process/" xmlns:diag="http://example.com/TMP" xmlns:tns="http://www.intalio.com/BPMS/Workflow/TaskManagementServices-20051109/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:PreviousProcessTaskManager="http://example.com/TMP/PreviousProcessTaskManager" xmlns:pnlk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" targetNamespace="http://example.com/TMP">
    <wsdl:import namespace="http://www.intalio.com/BPMS/Workflow/TaskManagementServices-20051109/" location="TaskManagementSystem.wsdl"/>
    <wsdl:import namespace="http://www.intalio.com/bpms/ubp" location="UserBusinessProcess.wsdl"/>
    <wsdl:import namespace="http://www.intalio.com/bpms/workflow/ib4p_20051115" location="TaskManagerProcess.wsdl"/>
    <pnlk:partnerLinkType name="TaskManagementProcessAndNextTaskManagerForTMPPortPlk">
        <pnlk:role name="TaskManagementProcess_for_NextTaskManager" portType="b4p:TMPPortType"/>
    </pnlk:partnerLinkType>
    <pnlk:partnerLinkType name="TaskManagementProcessAndTaskManagementSystemForPortTaskManagementServicesSOAPPlk">
        <pnlk:role name="TaskManagementSystem_for_TaskManagementProcess" portType="tns:TaskManagementServices"/>
    </pnlk:partnerLinkType>
    <pnlk:partnerLinkType name="TMPAndUBP">
        <pnlk:role name="TaskManagementProcess_for_UserBusinessProcessForUserBusinessProcessPort" portType="b4p:UserBusinessProcessPortType"/>
        <pnlk:role name="UserBusinessProcess_for_TaskManagementProcessForUserProcessPort" portType="UserBusinessProcess:userProcessPortType"/>
    </pnlk:partnerLinkType>
    <pnlk:partnerLinkType name="TaskManagementProcessAndUIFWForUIFWPortPlk">
        <pnlk:role name="TaskManagementProcess_for_UIFW" portType="b4p:UIFWPortType"/>
    </pnlk:partnerLinkType>
    <pnlk:partnerLinkType name="TaskManagementProcessAndPreviousProcessTaskManagerForTMPPortPlk">
        <pnlk:role name="PreviousProcessTaskManager_for_TaskManagementProcess" portType="b4p:TMPPortType"/>
    </pnlk:partnerLinkType>
</wsdl:definitions>